#!/bin/bash

#Automated benchmarking with mlucas for big.LITTLE architectures.
#Assumes environment is as follows (the setup script helps do this):
# * mlucas binary located at ~/mlucas
# * ~/primary and ~/secondary directories present containing mlucas.cfg and cpu from setup phase
# * Temperature plotter at ~/plotter
# plotter requires 'sensors', probably acquired via 'lm-sensors'

#Directory to store results
resdir="results"

#Define simultaneous tests
fft=(1024 2560 4608 7680 18432)
exponent=(20000047 49005071 87068977 143472073 332220523)
duration=(3600 7200 10800 14400 36000)
testcount=${#fft[@]}

#Create results dir, or early exit if it already exists
if [ -d ${resdir} ]; then
 echo "benchmark-results directory already exists, exiting to avoid a mess"
 exit 1
else
 mkdir ${resdir}
fi

#Find clusters from environment
cluster=()
if [ -d ~/primary ]; then cluster+=(primary); fi
if [ -d ~/secondary ]; then cluster+=(secondary); fi
if [ -d ~/tertiary ]; then cluster+=(tertiary); fi
if [ -d ~/quaternary ]; then cluster+=(quaternary); fi
clustercount=${#cluster[@]}

#Check environment is in order
if [ ! -f ~/plotter ]; then echo "plotter missing, possible setup error" && exit 1; fi
for (( j=0; j<${clustercount}; j++ )); do
 if [ -d ~/${cluster[$j]} ]; then
  if [ ! -e ~/${cluster[$j]}/mlucas.cfg ]; then echo "${cluster[$j]} mlucas.cfg missing, possible setup error" && exit 1; fi
  if [ ! -f ~/${cluster[$j]}/cpu ]; then echo "${cluster[$j]} cpu config missing, possible setup error" && exit 1; fi
 else
  echo "${cluster[$j]} directory missing, possible setup error" && exit 1
 fi
done

#Prep worktodo for benchmarking
for (( j=0; j<${clustercount}; j++ )); do
 if [ -f ~/${cluster[$j]}/worktodo.ini ]; then rm ~/${cluster[$j]}/worktodo.ini; fi
 ln -s ~/worktodo.ini ~/${cluster[$j]}/worktodo.ini
done

#Do tests
for (( i=0; i<${testcount}; i++ )); do

 #Edit worktodo
 echo "Test=${exponent[$i]}" >worktodo.ini

 #Start plotter
 ~/plotter "${resdir}/p${exponent[$i]}.temps" &

 #Start clusters
 for (( j=0; j<${clustercount}; j++ )); do
  cd ~/${cluster[$j]} && ~/mlucas -cpu $(cat ~/${cluster[$j]}/cpu) &
  sleep 1
 done

 #Sleep for test duration
 sleep 3
 date
 echo "Executing FFT ${fft[$i]}K, exponent ${exponent[$i]}, duration ~${duration[$i]} seconds"
 sleep ${duration[$i]}

 #Kill test
 pkill mlucas
 pkill plotter

 #Gather results and cleanup residuals
 for (( j=0; j<${clustercount}; j++ )); do
  #mlucas.cfg
  cp ~/${cluster[$j]}/mlucas.cfg ~/${resdir}/mlucas.${cluster[$j]}.cfg
  #results
  mv ~/${cluster[$j]}/p${exponent[$i]}.stat ~/${resdir}/p${fft[$i]}K.${cluster[$j]}.stat
  #Cleanup residuals
  rm ~/${cluster[$j]}/*${exponent[$i]}
 done

done

tar -f ~/${resdir}.tar ~/${resdir}
echo "Benchmarking complete, consider uploading ${resdir}.tar to mersenneforum.org to share the results"
